version: 2
jobs:
<<<<<<< HEAD
  setup_dependencies:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout:
      - restore_cache:
          key: deps-{{ checksum "requirements.lock" }}
      - run:
          command: |
            pip install --user -r requirements.lock
      - save_cache:
          key: deps-{{ checksum "requirements.lock" }}
          paths:
            - "~/.local"

  build:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.lock" }}
      - run:
          command: |
            python3 -m unittest -v

workflows:
  version: 2
  all:
    jobs:
      - setup_dependencies
      - build:
          requires:
            - setup_dependencies

            
            
=======
    setup_dependencies:
        docker:
            - image: circleci/python:3.8.1
        steps:
            - checkout

    test:
        docker:
            - image: circleci/python:3.8.1
        steps:
            - checkout
            - run:
                command: |
                    python3 -m unittest -v
workflows:
    version: 2
    all:
        jobs:
            - setup_dependencies
            - test:
                requires:
                    - setup_dependencies
                                    
>>>>>>> 20ebb2bc9859f4db0697510ff819ccfeb27038c3
