version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          command: |
            python3 -m unittest -v
workflows:
  version: 2
  all:
    jobs:
      - test